### ISSUE TITLE
トップページからブログへのリンク

### ISSUE THREAD

**Issue by lo48576** [titech-ssr/www.rogiken.org-root#17]
https://github.com/titech-ssr/www.rogiken.org-root/blob/344a3508a810472a3ca904228333e160beb0de3e/index.html#L75

feed に飛んでしまうので、トップページに飛ばした方がいいです

**Comment by lo48576** [comment]
あと `//` で始まるリンクは非推奨なので `https://` にした方がいいです(たぶんここに限らない)

**Comment by kcvlex** [comment]
倒しました
