### ISSUE TITLE
一部ページからロ技研の旧wikiへの切れたリンクが張られている

### ISSUE THREAD

**Issue by lo48576** [titech-ssr/www.rogiken.org-root#6]
[2016年新歓ページ](https://www.rogiken.org/shinkan/2016/)などから「[東京工業大学ロボット技術研究会 Wiki](http://3rd.rogiken.org/wiki/index.php?FrontPage)」へリンクが張られているが、これは今は亡き旧サーバへのリンクである。

新wiki作ったらそっちに張り直したい。

**Comment by 3tty0n** [comment]
#7 と内容が重複しています #6 を close するなりして対応するのがよいと思われます。

**Comment by l1048576** [comment]
minicon wikiって、ロ技研共通のwikiと別物かと思ってたんですが、同一のものだったでしょうか……？
(共通wikiのバックアップでgrepかけたところ、リンク以外にminiconっぽさが無かったので、別物かと思ってました)

**Comment by 3tty0n** [comment]
私は最近Joinしたので詳細はわかないのですが、リンク切れに関するissueは1つにまとめた方が追いやすいと思います。いかがでしょうか（他の方のコメント求む…）。

**Comment by 3tty0n** [comment]
もし、リンク単位でのリンク切れのissueを建てたいなら、文面を変えるなどして内容が違うissueとして建てるのがいいと思います。

> 2016年新歓ページなどから「東京工業大学ロボット技術研究会 Wiki」へリンクが張られているが、これは今は亡き旧サーバへのリンクである。

> minicon wikiのことはよく把握していないが、たぶんバックアップが残ってないと思われる。
新しく作るなり、リンクを消すなり、何らかの処置を行う必要があろう。

この文面と

> 2016年新歓ページなどから「東京工業大学ロボット技術研究会 Wiki」へリンクが張られているが、これは今は亡き旧サーバへのリンクである。

> 新wiki作ったらそっちに張り直したい。

この文面では結構似ているので、同一の内容だと誤解されてしまいそうです。

**Comment by l1048576** [comment]
ぽよ……コピペはまずかったですかね
修正します
