### ISSUE TITLE
トップに最近の活動・実績・お知らせ一覧を表示する

### ISSUE THREAD

**Issue by idt12312** [titech-ssr/www.rogiken.org-root#8]
「yy年mm月dd日 : 〇〇ロボコンに参加   △チームが優勝」
「yy年mm月dd日 : 工大祭で展示を行います」
みたいな感じ。
文字にリンク貼っといて、ブログの記事とかに飛ぶとよさそう。

どうですか？

**Comment by l1048576** [comment]
なるぽよ、良いと思います。

[トップページ](https://www.rogiken.org/)か[活動紹介](https://www.rogiken.org/activity/)のどちらかになると思いますが、どこが良いですかね……
(トップの方が目立ちそうではある)
